

Config.Skins = {
	['trucker'] = {
		['m'] = {
			headOverlays = {
			   ageing = {
				  opacity = 0,
				  style = 0,
				  color = 0,
				},
			   blush = {
				  opacity = 0,
				  style = 0,
				  color = 0,
				},
			   moleAndFreckles = {
				  opacity = 0.5,
				  style = 0,
				  color = 0,
				},
			   sunDamage = {
				  opacity = 0,
				  style = 0,
				  color = 0,
				},
			   beard = {
				  opacity = 1,
				  style = 8,
				  color = 20,
				},
			   complexion = {
				  opacity = 0,
				  style = 0,
				  color = 0,
				},
			   makeUp = {
				  opacity = 0,
				  style = 0,
				  color = 0,
				},
			   bodyBlemishes = {
				  opacity = 0,
				  style = 0,
				  color = 0,
				},
			   lipstick = {
				  opacity = 0,
				  style = 0,
				  color = 0,
				},
			   blemishes = {
				  opacity = 0,
				  style = 0,
				  color = 0,
				},
			   chestHair = {
				  opacity = 0,
				  style = 0,
				  color = 0,
				},
			   eyebrows = {
				  opacity = 1,
				  style = 30,
				  color = 54,
				},
			 },
			model = "mp_m_freemode_01",
			components = {
			   [1] = {
				  texture = 0,
				  component_id = 0,
				  drawable = 0,
				},
			   [2] = {
				  texture = 0,
				  component_id = 1,
				  drawable = 0,
				},
			   [3] = {
				  texture = 0,
				  component_id = 2,
				  drawable = 138,
				},
			   [4] = {
				  texture = 0,
				  component_id = 3,
				  drawable = 11,
				},
			   [5] = {
				  texture = 0,
				  component_id = 4,
				  drawable = 78,
				},
			   [6] = {
				  texture = 0,
				  component_id = 5,
				  drawable = 0,
				},
			   [7] = {
				  texture = 0,
				  component_id = 6,
				  drawable = 102,
				},
			   [8] = {
				  texture = 0,
				  component_id = 7,
				  drawable = 0,
				},
			   [9] = {
				  texture = 0,
				  component_id = 8,
				  drawable = 194,
				},
			   [10] = {
				  texture = 0,
				  component_id = 9,
				  drawable = 0,
				},
			   [11] = {
				  texture = 0,
				  component_id = 10,
				  drawable = 0,
				},
			   [12] = {
				  texture = 0,
				  component_id = 11,
				  drawable = 240,
				},
			 },
			hair = {
			   color = 20,
			   highlight = 20,
			   style = 138,
			 },
			faceFeatures = {
			   jawBoneWidth = 0.5,
			   nosePeakHigh = -0.3,
			   noseBoneTwist = -0.3,
			   eyesOpening = 0.8,
			   cheeksWidth = 0.5,
			   eyeBrownHigh = 0,
			   cheeksBoneHigh = -0.2,
			   chinBoneSize = 0,
			   noseBoneHigh = 0.1,
			   lipsThickness = 0,
			   eyeBrownForward = 0,
			   chinBoneLenght = 0,
			   noseWidth = -0.7,
			   chinBoneLowering = 0,
			   nosePeakLowering = 0.1,
			   chinHole = 1,
			   cheeksBoneWidth = -1,
			   jawBoneBackSize = -0.6,
			   neckThickness = 1,
			   nosePeakSize = -0.1,
			 },
			headBlend = {
			   skinSecond = 0,
			   skinMix = 0,
			   shapeSecond = 45,
			   skinFirst = 7,
			   shapeFirst = 45,
			   shapeMix = 0.4,
			 },
			props = {
			   [1] = {
				  texture = -1,
				  prop_id = 0,
				  drawable = -1,
				},
			   [2] = {
				  texture = -1,
				  prop_id = 1,
				  drawable = -1,
				},
			   [3] = {
				  texture = -1,
				  prop_id = 2,
				  drawable = -1,
				},
			   [4] = {
				  texture = 0,
				  prop_id = 6,
				  drawable = 37,
				},
			   [5] = {
				  texture = -1,
				  prop_id = 7,
				  drawable = -1,
				},
			 },
			eyeColor = 24,
			tattoos = {
			 },
		  },

		  ['f'] = {
			faceFeatures = {
			   noseBoneTwist = 0,
			   cheeksBoneWidth = 0,
			   cheeksBoneHigh = 0,
			   cheeksWidth = 0,
			   noseWidth = -1,
			   jawBoneBackSize = 0,
			   eyesOpening = 0,
			   chinBoneLenght = 1,
			   jawBoneWidth = 0,
			   nosePeakSize = 0.5,
			   chinHole = 0,
			   eyeBrownHigh = -0.5,
			   noseBoneHigh = 0,
			   nosePeakHigh = 0.4,
			   lipsThickness = -0.4,
			   chinBoneSize = 0,
			   nosePeakLowering = 0,
			   eyeBrownForward = -0.8,
			   chinBoneLowering = -1,
			   neckThickness = -0.5,
			 },
			tattoos = {
			 },
			headBlend = {
			   skinMix = 1,
			   shapeSecond = 21,
			   shapeFirst = 0,
			   skinFirst = 0,
			   skinSecond = 21,
			   shapeMix = 1,
			 },
			hair = {
			   highlight = 0,
			   style = 10,
			   color = 0,
			 },
			headOverlays = {
			   eyebrows = {
				  opacity = 0.7,
				  style = 2,
				  color = 60,
				},
			   moleAndFreckles = {
				  opacity = 1,
				  style = 5,
				  color = 0,
				},
			   chestHair = {
				  opacity = 0,
				  style = 0,
				  color = 0,
				},
			   makeUp = {
				  opacity = 0.8,
				  style = 3,
				  color = 23,
				},
			   ageing = {
				  opacity = 0,
				  style = 0,
				  color = 0,
				},
			   lipstick = {
				  opacity = 0.5,
				  style = 1,
				  color = 24,
				},
			   blush = {
				  opacity = 0.3,
				  style = 6,
				  color = 6,
				},
			   sunDamage = {
				  opacity = 0.3,
				  style = 1,
				  color = 0,
				},
			   bodyBlemishes = {
				  opacity = 0,
				  style = 0,
				  color = 0,
				},
			   blemishes = {
				  opacity = 0,
				  style = 0,
				  color = 0,
				},
			   beard = {
				  opacity = 0,
				  style = 0,
				  color = 0,
				},
			   complexion = {
				  opacity = 1,
				  style = 9,
				  color = 0,
				},
			 },
			props = {
			   [1] = {
				  texture = -1,
				  prop_id = 0,
				  drawable = -1,
				},
			   [2] = {
				  texture = -1,
				  prop_id = 1,
				  drawable = -1,
				},
			   [3] = {
				  texture = -1,
				  prop_id = 2,
				  drawable = -1,
				},
			   [4] = {
				  texture = -1,
				  prop_id = 6,
				  drawable = -1,
				},
			   [5] = {
				  texture = -1,
				  prop_id = 7,
				  drawable = -1,
				},
			 },
			model = "mp_f_freemode_01",
			components = {
			   [1] = {
				  component_id = 0,
				  texture = 0,
				  drawable = 0,
				},
			   [2] = {
				  component_id = 1,
				  texture = 0,
				  drawable = 0,
				},
			   [3] = {
				  component_id = 2,
				  texture = 0,
				  drawable = 10,
				},
			   [4] = {
				  component_id = 3,
				  texture = 0,
				  drawable = 0,
				},
			   [5] = {
				  component_id = 4,
				  texture = 0,
				  drawable = 84,
				},
			   [6] = {
				  component_id = 5,
				  texture = 0,
				  drawable = 0,
				},
			   [7] = {
				  component_id = 6,
				  texture = 0,
				  drawable = 120,
				},
			   [8] = {
				  component_id = 7,
				  texture = 0,
				  drawable = 85,
				},
			   [9] = {
				  component_id = 8,
				  texture = 0,
				  drawable = 244,
				},
			   [10] = {
				  component_id = 9,
				  texture = 0,
				  drawable = 0,
				},
			   [11] = {
				  component_id = 10,
				  texture = 0,
				  drawable = 0,
				},
			   [12] = {
				  component_id = 11,
				  texture = 4,
				  drawable = 464,
				},
			 },
			eyeColor = 8,
		  }
	},
	['pizza']  ={
		['m'] = {
			tattoos = {
			 },
			headOverlays = {
			   sunDamage = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   beard = {
				  style = 3,
				  color = 0,
				  opacity = 1,
				},
			   ageing = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   makeUp = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   eyebrows = {
				  style = 30,
				  color = 0,
				  opacity = 1,
				},
			   moleAndFreckles = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   complexion = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   lipstick = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   bodyBlemishes = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   blush = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   blemishes = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   chestHair = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			 },
			model = "mp_m_freemode_01",
			props = {
			   [1] = {
				  prop_id = 0,
				  texture = 0,
				  drawable = 20,
				},
			   [2] = {
				  prop_id = 1,
				  texture = 0,
				  drawable = 0,
				},
			   [3] = {
				  prop_id = 2,
				  texture = -1,
				  drawable = -1,
				},
			   [4] = {
				  prop_id = 6,
				  texture = -1,
				  drawable = -1,
				},
			   [5] = {
				  prop_id = 7,
				  texture = -1,
				  drawable = -1,
				},
			 },
			hair = {
			   highlight = 54,
			   style = 184,
			   color = 54,
			 },
			components = {
			   [1] = {
				  drawable = 0,
				  texture = 0,
				  component_id = 0,
				},
			   [2] = {
				  drawable = 0,
				  texture = 0,
				  component_id = 1,
				},
			   [3] = {
				  drawable = 184,
				  texture = 0,
				  component_id = 2,
				},
			   [4] = {
				  drawable = 85,
				  texture = 0,
				  component_id = 3,
				},
			   [5] = {
				  drawable = 114,
				  texture = 2,
				  component_id = 4,
				},
			   [6] = {
				  drawable = 0,
				  texture = 0,
				  component_id = 5,
				},
			   [7] = {
				  drawable = 28,
				  texture = 1,
				  component_id = 6,
				},
			   [8] = {
				  drawable = 0,
				  texture = 0,
				  component_id = 7,
				},
			   [9] = {
				  drawable = 15,
				  texture = 0,
				  component_id = 8,
				},
			   [10] = {
				  drawable = 0,
				  texture = 0,
				  component_id = 9,
				},
			   [11] = {
				  drawable = 0,
				  texture = 0,
				  component_id = 10,
				},
			   [12] = {
				  drawable = 438,
				  texture = 1,
				  component_id = 11,
				},
			 },
			eyeColor = 0,
			faceFeatures = {
			   nosePeakLowering = 0,
			   noseBoneTwist = 0,
			   noseWidth = 0,
			   noseBoneHigh = 0,
			   cheeksWidth = 0,
			   eyeBrownForward = 0,
			   cheeksBoneHigh = 0,
			   nosePeakSize = 0,
			   chinBoneLenght = 0,
			   lipsThickness = 0,
			   eyesOpening = 0,
			   cheeksBoneWidth = 0,
			   jawBoneBackSize = 0,
			   eyeBrownHigh = 0,
			   chinHole = 0,
			   nosePeakHigh = 0,
			   jawBoneWidth = 0,
			   neckThickness = 0,
			   chinBoneSize = 0,
			   chinBoneLowering = 0,
			 },
			headBlend = {
			   shapeMix = 0,
			   shapeFirst = 2,
			   skinFirst = 0,
			   shapeSecond = 0,
			   skinSecond = 14,
			   skinMix = 1,
			 },
		  },
		  ['f'] = {
			props = {
			   [1] = {
				  texture = 1,
				  prop_id = 0,
				  drawable = 49,
				},
			   [2] = {
				  texture = 0,
				  prop_id = 1,
				  drawable = 18,
				},
			   [3] = {
				  texture = -1,
				  prop_id = 2,
				  drawable = -1,
				},
			   [4] = {
				  texture = -1,
				  prop_id = 6,
				  drawable = -1,
				},
			   [5] = {
				  texture = -1,
				  prop_id = 7,
				  drawable = -1,
				},
			 },
			headOverlays = {
			   moleAndFreckles = {
				  style = 12,
				  opacity = 0.8,
				  color = 0,
				},
			   eyebrows = {
				  style = 32,
				  opacity = 0.7,
				  color = 52,
				},
			   sunDamage = {
				  style = 0,
				  opacity = 0,
				  color = 0,
				},
			   bodyBlemishes = {
				  style = 0,
				  opacity = 0,
				  color = 0,
				},
			   lipstick = {
				  style = 0,
				  opacity = 0.1,
				  color = 22,
				},
			   complexion = {
				  style = 0,
				  opacity = 0,
				  color = 0,
				},
			   ageing = {
				  style = 0,
				  opacity = 0,
				  color = 0,
				},
			   blemishes = {
				  style = 0,
				  opacity = 0,
				  color = 0,
				},
			   chestHair = {
				  style = 0,
				  opacity = 0,
				  color = 0,
				},
			   beard = {
				  style = 0,
				  opacity = 0,
				  color = 0,
				},
			   makeUp = {
				  style = 0,
				  opacity = 0,
				  color = 0,
				},
			   blush = {
				  style = 0,
				  opacity = 0,
				  color = 0,
				},
			 },
			model = "mp_f_freemode_01",
			eyeColor = 8,
			faceFeatures = {
			   neckThickness = -0.5,
			   nosePeakHigh = 0.4,
			   eyeBrownForward = -0.8,
			   chinHole = 0,
			   chinBoneLowering = -1,
			   jawBoneWidth = 0,
			   eyesOpening = -0.6,
			   noseBoneHigh = 0,
			   nosePeakSize = 0.5,
			   cheeksWidth = 0,
			   lipsThickness = 0,
			   chinBoneLenght = 1,
			   noseWidth = -1,
			   chinBoneSize = 0,
			   cheeksBoneHigh = 0,
			   noseBoneTwist = 0,
			   eyeBrownHigh = -0.5,
			   cheeksBoneWidth = 0,
			   jawBoneBackSize = 0,
			   nosePeakLowering = 0,
			 },
			hair = {
			   style = 94,
			   highlight = 18,
			   color = 19,
			 },
			components = {
			   [1] = {
				  drawable = 0,
				  component_id = 0,
				  texture = 0,
				},
			   [2] = {
				  drawable = 0,
				  component_id = 1,
				  texture = 0,
				},
			   [3] = {
				  drawable = 94,
				  component_id = 2,
				  texture = 0,
				},
			   [4] = {
				  drawable = 113,
				  component_id = 3,
				  texture = 0,
				},
			   [5] = {
				  drawable = 60,
				  component_id = 4,
				  texture = 0,
				},
			   [6] = {
				  drawable = 0,
				  component_id = 5,
				  texture = 0,
				},
			   [7] = {
				  drawable = 13,
				  component_id = 6,
				  texture = 11,
				},
			   [8] = {
				  drawable = 0,
				  component_id = 7,
				  texture = 0,
				},
			   [9] = {
				  drawable = 14,
				  component_id = 8,
				  texture = 0,
				},
			   [10] = {
				  drawable = 0,
				  component_id = 9,
				  texture = 0,
				},
			   [11] = {
				  drawable = 0,
				  component_id = 10,
				  texture = 0,
				},
			   [12] = {
				  drawable = 362,
				  component_id = 11,
				  texture = 1,
				},
			 },
			headBlend = {
			   skinSecond = 33,
			   shapeMix = 0.6,
			   skinMix = 0.6,
			   shapeSecond = 21,
			   skinFirst = 33,
			   shapeFirst = 20,
			 },
			tattoos = {
			 },
		  }	
	},
	['fueler'] = {
		['m'] = {
			eyeColor = 26,
			faceFeatures = {
			   eyesOpening = 0,
			   lipsThickness = -0.4,
			   cheeksWidth = 0.5,
			   noseBoneHigh = 0.1,
			   nosePeakHigh = 0,
			   jawBoneBackSize = -0.2,
			   chinBoneLowering = 0,
			   chinHole = 0,
			   eyeBrownForward = 0,
			   noseBoneTwist = -0.3,
			   jawBoneWidth = -0.2,
			   nosePeakSize = -0.1,
			   chinBoneLenght = 0,
			   nosePeakLowering = 0.1,
			   cheeksBoneWidth = -1,
			   noseWidth = -0.5,
			   chinBoneSize = 0,
			   neckThickness = 0,
			   cheeksBoneHigh = -0.2,
			   eyeBrownHigh = 0,
			 },
			components = {
			   [1] = {
				  texture = 0,
				  component_id = 0,
				  drawable = 0,
				},
			   [2] = {
				  texture = 0,
				  component_id = 1,
				  drawable = 0,
				},
			   [3] = {
				  texture = 0,
				  component_id = 2,
				  drawable = 12,
				},
			   [4] = {
				  texture = 0,
				  component_id = 3,
				  drawable = 60,
				},
			   [5] = {
				  texture = 3,
				  component_id = 4,
				  drawable = 103,
				},
			   [6] = {
				  texture = 0,
				  component_id = 5,
				  drawable = 0,
				},
			   [7] = {
				  texture = 0,
				  component_id = 6,
				  drawable = 75,
				},
			   [8] = {
				  texture = 0,
				  component_id = 7,
				  drawable = 0,
				},
			   [9] = {
				  texture = 0,
				  component_id = 8,
				  drawable = 15,
				},
			   [10] = {
				  texture = 0,
				  component_id = 9,
				  drawable = 0,
				},
			   [11] = {
				  texture = 0,
				  component_id = 10,
				  drawable = 0,
				},
			   [12] = {
				  texture = 3,
				  component_id = 11,
				  drawable = 263,
				},
			 },
			props = {
			   [1] = {
				  texture = -1,
				  prop_id = 0,
				  drawable = -1,
				},
			   [2] = {
				  texture = -1,
				  prop_id = 1,
				  drawable = -1,
				},
			   [3] = {
				  texture = -1,
				  prop_id = 2,
				  drawable = -1,
				},
			   [4] = {
				  texture = -1,
				  prop_id = 6,
				  drawable = -1,
				},
			   [5] = {
				  texture = -1,
				  prop_id = 7,
				  drawable = -1,
				},
			 },
			model = "mp_m_freemode_01",
			tattoos = {
			   ZONE_LEFT_ARM = {
				  [1] = {
					 zone = "ZONE_LEFT_ARM",
					 hashMale = "MP_LR_Tat_022_M",
					 collection = "mplowrider2_overlays",
					 hashFemale = "MP_LR_Tat_022_F",
					 name = "TAT_S2_022",
					 label = "My Crazy Life",
				   },
				},
			   ZONE_RIGHT_ARM = {
				  [1] = {
					 zone = "ZONE_RIGHT_ARM",
					 hashMale = "MP_MP_ImportExport_Tat_003_M",
					 collection = "mpimportexport_overlays",
					 hashFemale = "MP_MP_ImportExport_Tat_003_F",
					 name = "TAT_IE_003",
					 label = "Mechanical Sleeve",
				   },
				},
			 },
			hair = {
			   color = 28,
			   highlight = 38,
			   style = 12,
			 },
			headOverlays = {
			   moleAndFreckles = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   complexion = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   blemishes = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   makeUp = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   lipstick = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   blush = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   beard = {
				  color = 0,
				  opacity = 1,
				  style = 6,
				},
			   bodyBlemishes = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   sunDamage = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   eyebrows = {
				  color = 0,
				  opacity = 1,
				  style = 30,
				},
			   chestHair = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   ageing = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			 },
			headBlend = {
			   shapeSecond = 20,
			   shapeFirst = 21,
			   shapeMix = 0.4,
			   skinFirst = 21,
			   skinSecond = 0,
			   skinMix = 0.3,
			 },
		  },

		  ['f'] = {
			faceFeatures = {
			   nosePeakHigh = 0,
			   jawBoneBackSize = 0,
			   eyeBrownForward = 0,
			   eyesOpening = 0,
			   nosePeakSize = 0,
			   chinBoneSize = 0,
			   cheeksWidth = 0,
			   chinBoneLenght = 0,
			   noseBoneTwist = 0,
			   nosePeakLowering = 0,
			   neckThickness = 0,
			   jawBoneWidth = 0,
			   chinBoneLowering = 0,
			   cheeksBoneWidth = 0,
			   noseBoneHigh = 0,
			   chinHole = 0,
			   eyeBrownHigh = 0,
			   lipsThickness = 0,
			   cheeksBoneHigh = 0,
			   noseWidth = 0,
			 },
			headBlend = {
			   shapeSecond = 0,
			   skinFirst = 12,
			   skinSecond = 0,
			   shapeFirst = 21,
			   shapeMix = 0,
			   skinMix = 0,
			 },
			model = "mp_f_freemode_01",
			hair = {
			   highlight = 55,
			   style = 34,
			   color = 4,
			 },
			tattoos = {
			 },
			eyeColor = 3,
			props = {
			   [1] = {
				  prop_id = 0,
				  texture = -1,
				  drawable = -1,
				},
			   [2] = {
				  prop_id = 1,
				  texture = -1,
				  drawable = -1,
				},
			   [3] = {
				  prop_id = 2,
				  texture = -1,
				  drawable = -1,
				},
			   [4] = {
				  prop_id = 6,
				  texture = -1,
				  drawable = -1,
				},
			   [5] = {
				  prop_id = 7,
				  texture = -1,
				  drawable = -1,
				},
			 },
			headOverlays = {
			   chestHair = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   ageing = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   complexion = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   beard = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   blush = {
				  style = 1,
				  color = 5,
				  opacity = 0.6,
				},
			   moleAndFreckles = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   makeUp = {
				  style = 4,
				  color = 3,
				  opacity = 0.8,
				},
			   eyebrows = {
				  style = 1,
				  color = 5,
				  opacity = 0.9,
				},
			   bodyBlemishes = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   blemishes = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   lipstick = {
				  style = 2,
				  color = 2,
				  opacity = 0.6,
				},
			   sunDamage = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			 },
			components = {
			   [1] = {
				  component_id = 0,
				  texture = 0,
				  drawable = 0,
				},
			   [2] = {
				  component_id = 1,
				  texture = 0,
				  drawable = 0,
				},
			   [3] = {
				  component_id = 2,
				  texture = 0,
				  drawable = 34,
				},
			   [4] = {
				  component_id = 3,
				  texture = 0,
				  drawable = 23,
				},
			   [5] = {
				  component_id = 4,
				  texture = 3,
				  drawable = 62,
				},
			   [6] = {
				  component_id = 5,
				  texture = 0,
				  drawable = 0,
				},
			   [7] = {
				  component_id = 6,
				  texture = 0,
				  drawable = 66,
				},
			   [8] = {
				  component_id = 7,
				  texture = 0,
				  drawable = 90,
				},
			   [9] = {
				  component_id = 8,
				  texture = 0,
				  drawable = 14,
				},
			   [10] = {
				  component_id = 9,
				  texture = 0,
				  drawable = 0,
				},
			   [11] = {
				  component_id = 10,
				  texture = 0,
				  drawable = 0,
				},
			   [12] = {
				  component_id = 11,
				  texture = 3,
				  drawable = 172,
				},
			 },
		  }
	},
	['airline'] = {
		['m'] = {
			eyeColor = 26,
			faceFeatures = {
			   eyesOpening = 0,
			   lipsThickness = -0.4,
			   cheeksWidth = 0.5,
			   noseBoneHigh = 0.1,
			   nosePeakHigh = 0,
			   jawBoneBackSize = -0.2,
			   chinBoneLowering = 0,
			   chinHole = 0,
			   eyeBrownForward = 0,
			   noseBoneTwist = -0.3,
			   jawBoneWidth = -0.2,
			   nosePeakSize = -0.1,
			   chinBoneLenght = 0,
			   nosePeakLowering = 0.1,
			   cheeksBoneWidth = -1,
			   noseWidth = -0.5,
			   chinBoneSize = 0,
			   neckThickness = 0,
			   cheeksBoneHigh = -0.2,
			   eyeBrownHigh = 0,
			 },
			components = {
			   [1] = {
				  texture = 0,
				  component_id = 0,
				  drawable = 0,
				},
			   [2] = {
				  texture = 0,
				  component_id = 1,
				  drawable = 0,
				},
			   [3] = {
				  texture = 0,
				  component_id = 2,
				  drawable = 12,
				},
			   [4] = {
				  texture = 0,
				  component_id = 3,
				  drawable = 4,
				},
			   [5] = {
				  texture = 0,
				  component_id = 4,
				  drawable = 92,
				},
			   [6] = {
				  texture = 0,
				  component_id = 5,
				  drawable = 0,
				},
			   [7] = {
				  texture = 0,
				  component_id = 6,
				  drawable = 10,
				},
			   [8] = {
				  texture = 11,
				  component_id = 7,
				  drawable = 113,
				},
			   [9] = {
				  texture = 0,
				  component_id = 8,
				  drawable = 15,
				},
			   [10] = {
				  texture = 0,
				  component_id = 9,
				  drawable = 0,
				},
			   [11] = {
				  texture = 0,
				  component_id = 10,
				  drawable = 0,
				},
			   [12] = {
				  texture = 0,
				  component_id = 11,
				  drawable = 519,
				},
			 },
			props = {
			   [1] = {
				  texture = 5,
				  prop_id = 0,
				  drawable = 161,
				},
			   [2] = {
				  texture = 4,
				  prop_id = 1,
				  drawable = 20,
				},
			   [3] = {
				  texture = -1,
				  prop_id = 2,
				  drawable = -1,
				},
			   [4] = {
				  texture = -1,
				  prop_id = 6,
				  drawable = -1,
				},
			   [5] = {
				  texture = -1,
				  prop_id = 7,
				  drawable = -1,
				},
			 },
			model = "mp_m_freemode_01",
			tattoos = {
			   ZONE_LEFT_ARM = {
				  [1] = {
					 zone = "ZONE_LEFT_ARM",
					 hashMale = "MP_LR_Tat_022_M",
					 collection = "mplowrider2_overlays",
					 hashFemale = "MP_LR_Tat_022_F",
					 name = "TAT_S2_022",
					 label = "My Crazy Life",
				   },
				},
			   ZONE_RIGHT_ARM = {
				  [1] = {
					 zone = "ZONE_RIGHT_ARM",
					 hashMale = "MP_MP_ImportExport_Tat_003_M",
					 collection = "mpimportexport_overlays",
					 hashFemale = "MP_MP_ImportExport_Tat_003_F",
					 name = "TAT_IE_003",
					 label = "Mechanical Sleeve",
				   },
				},
			 },
			hair = {
			   color = 28,
			   highlight = 38,
			   style = 12,
			 },
			headOverlays = {
			   moleAndFreckles = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   complexion = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   blemishes = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   makeUp = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   lipstick = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   blush = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   beard = {
				  color = 0,
				  opacity = 1,
				  style = 6,
				},
			   bodyBlemishes = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   sunDamage = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   eyebrows = {
				  color = 0,
				  opacity = 1,
				  style = 30,
				},
			   chestHair = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   ageing = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			 },
			headBlend = {
			   shapeSecond = 20,
			   shapeFirst = 21,
			   shapeMix = 0.4,
			   skinFirst = 21,
			   skinSecond = 0,
			   skinMix = 0.3,
			 },
		  },

		  ['f'] = {
			faceFeatures = {
			   nosePeakHigh = 0,
			   jawBoneBackSize = 0,
			   eyeBrownForward = 0,
			   eyesOpening = 0,
			   nosePeakSize = 0,
			   chinBoneSize = 0,
			   cheeksWidth = 0,
			   chinBoneLenght = 0,
			   noseBoneTwist = 0,
			   nosePeakLowering = 0,
			   neckThickness = 0,
			   jawBoneWidth = 0,
			   chinBoneLowering = 0,
			   cheeksBoneWidth = 0,
			   noseBoneHigh = 0,
			   chinHole = 0,
			   eyeBrownHigh = 0,
			   lipsThickness = 0,
			   cheeksBoneHigh = 0,
			   noseWidth = 0,
			 },
			headBlend = {
			   shapeSecond = 0,
			   skinFirst = 12,
			   skinSecond = 0,
			   shapeFirst = 21,
			   shapeMix = 0,
			   skinMix = 0,
			 },
			model = "mp_f_freemode_01",
			hair = {
			   highlight = 55,
			   style = 34,
			   color = 4,
			 },
			tattoos = {
			 },
			eyeColor = 3,
			props = {
			   [1] = {
				  prop_id = 0,
				  texture = 5,
				  drawable = 118,
				},
			   [2] = {
				  prop_id = 1,
				  texture = -1,
				  drawable = -1,
				},
			   [3] = {
				  prop_id = 2,
				  texture = -1,
				  drawable = -1,
				},
			   [4] = {
				  prop_id = 6,
				  texture = -1,
				  drawable = -1,
				},
			   [5] = {
				  prop_id = 7,
				  texture = -1,
				  drawable = -1,
				},
			 },
			headOverlays = {
			   chestHair = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   ageing = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   complexion = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   beard = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   blush = {
				  style = 1,
				  color = 5,
				  opacity = 0.6,
				},
			   moleAndFreckles = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   makeUp = {
				  style = 4,
				  color = 3,
				  opacity = 0.8,
				},
			   eyebrows = {
				  style = 1,
				  color = 5,
				  opacity = 0.9,
				},
			   bodyBlemishes = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   blemishes = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   lipstick = {
				  style = 2,
				  color = 2,
				  opacity = 0.6,
				},
			   sunDamage = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			 },
			components = {
			   [1] = {
				  component_id = 0,
				  texture = 0,
				  drawable = 0,
				},
			   [2] = {
				  component_id = 1,
				  texture = 0,
				  drawable = 0,
				},
			   [3] = {
				  component_id = 2,
				  texture = 0,
				  drawable = 34,
				},
			   [4] = {
				  component_id = 3,
				  texture = 0,
				  drawable = 14,
				},
			   [5] = {
				  component_id = 4,
				  texture = 0,
				  drawable = 7,
				},
			   [6] = {
				  component_id = 5,
				  texture = 0,
				  drawable = 0,
				},
			   [7] = {
				  component_id = 6,
				  texture = 0,
				  drawable = 0,
				},
			   [8] = {
				  component_id = 7,
				  texture = 0,
				  drawable = 32,
				},
			   [9] = {
				  component_id = 8,
				  texture = 0,
				  drawable = 14,
				},
			   [10] = {
				  component_id = 9,
				  texture = 0,
				  drawable = 0,
				},
			   [11] = {
				  component_id = 10,
				  texture = 0,
				  drawable = 0,
				},
			   [12] = {
				  component_id = 11,
				  texture = 5,
				  drawable = 478,
				},
			 },
		  }
	},
	['fisher'] = {
		['m'] = {
			model = "mp_m_freemode_01",
			headBlend = {
			   shapeSecond = 21,
			   skinFirst = 21,
			   skinMix = 0.3,
			   shapeFirst = 31,
			   shapeMix = 0.1,
			   skinSecond = 17,
			 },
			tattoos = {
			   ZONE_HEAD = {
				  [1] = {
					 zone = "ZONE_HEAD",
					 hashMale = "mpHeist3_Tat_019_M",
					 hashFemale = "mpHeist3_Tat_019_F",
					 label = "Teddy Bear",
					 name = "TAT_H3_019",
					 collection = "mpheist3_overlays",
				   },
				  [2] = {
					 zone = "ZONE_HEAD",
					 hashMale = "mpHeist3_Tat_042_M",
					 hashFemale = "mpHeist3_Tat_042_F",
					 label = "Hearts",
					 name = "TAT_H3_042",
					 collection = "mpheist3_overlays",
				   },
				},
			 },
			faceFeatures = {
			   nosePeakLowering = 0.1,
			   cheeksWidth = 0.5,
			   jawBoneBackSize = -1,
			   noseBoneTwist = -0.3,
			   eyeBrownForward = 0,
			   chinHole = 0,
			   eyesOpening = 0.3,
			   chinBoneLenght = 0,
			   eyeBrownHigh = -0.3,
			   lipsThickness = -0.5,
			   noseWidth = -0.8,
			   neckThickness = 0.1,
			   chinBoneSize = 0,
			   cheeksBoneWidth = -0.7,
			   chinBoneLowering = -0.4,
			   nosePeakSize = -0.3,
			   nosePeakHigh = 0.1,
			   cheeksBoneHigh = -0.3,
			   noseBoneHigh = 0,
			   jawBoneWidth = -0.3,
			 },
			components = {
			   [1] = {
				  drawable = 0,
				  component_id = 0,
				  texture = 0,
				},
			   [2] = {
				  drawable = 0,
				  component_id = 1,
				  texture = 0,
				},
			   [3] = {
				  drawable = 31,
				  component_id = 2,
				  texture = 0,
				},
			   [4] = {
				  drawable = 30,
				  component_id = 3,
				  texture = 0,
				},
			   [5] = {
				  drawable = 153,
				  component_id = 4,
				  texture = 3,
				},
			   [6] = {
				  drawable = 0,
				  component_id = 5,
				  texture = 0,
				},
			   [7] = {
				  drawable = 101,
				  component_id = 6,
				  texture = 0,
				},
			   [8] = {
				  drawable = 0,
				  component_id = 7,
				  texture = 0,
				},
			   [9] = {
				  drawable = 15,
				  component_id = 8,
				  texture = 0,
				},
			   [10] = {
				  drawable = 0,
				  component_id = 9,
				  texture = 0,
				},
			   [11] = {
				  drawable = 0,
				  component_id = 10,
				  texture = 0,
				},
			   [12] = {
				  drawable = 439,
				  component_id = 11,
				  texture = 3,
				},
			 },
			eyeColor = 11,
			headOverlays = {
			   complexion = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   sunDamage = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   makeUp = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   ageing = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   blush = {
				  color = 3,
				  opacity = 0.6,
				  style = 1,
				},
			   bodyBlemishes = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   blemishes = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   moleAndFreckles = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   beard = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   chestHair = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   lipstick = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   eyebrows = {
				  color = 0,
				  opacity = 0.7,
				  style = 5,
				},
			 },
			hair = {
			   color = 8,
			   highlight = 31,
			   style = 31,
			 },
			props = {
			   [1] = {
				  drawable = -1,
				  prop_id = 0,
				  texture = -1,
				},
			   [2] = {
				  drawable = 5,
				  prop_id = 1,
				  texture = 2,
				},
			   [3] = {
				  drawable = 5,
				  prop_id = 2,
				  texture = 1,
				},
			   [4] = {
				  drawable = -1,
				  prop_id = 6,
				  texture = -1,
				},
			   [5] = {
				  drawable = -1,
				  prop_id = 7,
				  texture = -1,
				},
			 },
		  },
		  ['f'] = {
			faceFeatures = {
			   nosePeakHigh = 0,
			   jawBoneBackSize = 0,
			   eyeBrownForward = 0,
			   eyesOpening = 0,
			   nosePeakSize = 0,
			   chinBoneSize = 0,
			   cheeksWidth = 0,
			   chinBoneLenght = 0,
			   noseBoneTwist = 0,
			   nosePeakLowering = 0,
			   neckThickness = 0,
			   jawBoneWidth = 0,
			   chinBoneLowering = 0,
			   cheeksBoneWidth = 0,
			   noseBoneHigh = 0,
			   chinHole = 0,
			   eyeBrownHigh = 0,
			   lipsThickness = 0,
			   cheeksBoneHigh = 0,
			   noseWidth = 0,
			 },
			headBlend = {
			   shapeSecond = 0,
			   skinFirst = 12,
			   skinSecond = 0,
			   shapeFirst = 21,
			   shapeMix = 0,
			   skinMix = 0,
			 },
			model = "mp_f_freemode_01",
			hair = {
			   highlight = 55,
			   style = 34,
			   color = 4,
			 },
			tattoos = {
			 },
			eyeColor = 3,
			props = {
			   [1] = {
				  prop_id = 0,
				  texture = -1,
				  drawable = -1,
				},
			   [2] = {
				  prop_id = 1,
				  texture = -1,
				  drawable = -1,
				},
			   [3] = {
				  prop_id = 2,
				  texture = -1,
				  drawable = -1,
				},
			   [4] = {
				  prop_id = 6,
				  texture = -1,
				  drawable = -1,
				},
			   [5] = {
				  prop_id = 7,
				  texture = -1,
				  drawable = -1,
				},
			 },
			headOverlays = {
			   chestHair = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   ageing = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   complexion = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   beard = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   blush = {
				  style = 1,
				  color = 5,
				  opacity = 0.6,
				},
			   moleAndFreckles = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   makeUp = {
				  style = 4,
				  color = 3,
				  opacity = 0.8,
				},
			   eyebrows = {
				  style = 1,
				  color = 5,
				  opacity = 0.9,
				},
			   bodyBlemishes = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   blemishes = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   lipstick = {
				  style = 2,
				  color = 2,
				  opacity = 0.6,
				},
			   sunDamage = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			 },
			components = {
			   [1] = {
				  component_id = 0,
				  texture = 0,
				  drawable = 0,
				},
			   [2] = {
				  component_id = 1,
				  texture = 0,
				  drawable = 0,
				},
			   [3] = {
				  component_id = 2,
				  texture = 0,
				  drawable = 34,
				},
			   [4] = {
				  component_id = 3,
				  texture = 0,
				  drawable = 48,
				},
			   [5] = {
				  component_id = 4,
				  texture = 3,
				  drawable = 115,
				},
			   [6] = {
				  component_id = 5,
				  texture = 0,
				  drawable = 0,
				},
			   [7] = {
				  component_id = 6,
				  texture = 0,
				  drawable = 66,
				},
			   [8] = {
				  component_id = 7,
				  texture = 0,
				  drawable = 85,
				},
			   [9] = {
				  component_id = 8,
				  texture = 0,
				  drawable = 14,
				},
			   [10] = {
				  component_id = 9,
				  texture = 0,
				  drawable = 67,
				},
			   [11] = {
				  component_id = 10,
				  texture = 0,
				  drawable = 0,
				},
			   [12] = {
				  component_id = 11,
				  texture = 0,
				  drawable = 200,
				},
			 },
		  },
	},
	['miner'] = {
		['m'] = {
			eyeColor = 26,
			faceFeatures = {
			   eyesOpening = 0,
			   lipsThickness = -0.4,
			   cheeksWidth = 0.5,
			   noseBoneHigh = 0.1,
			   nosePeakHigh = 0,
			   jawBoneBackSize = -0.2,
			   chinBoneLowering = 0,
			   chinHole = 0,
			   eyeBrownForward = 0,
			   noseBoneTwist = -0.3,
			   jawBoneWidth = -0.2,
			   nosePeakSize = -0.1,
			   chinBoneLenght = 0,
			   nosePeakLowering = 0.1,
			   cheeksBoneWidth = -1,
			   noseWidth = -0.5,
			   chinBoneSize = 0,
			   neckThickness = 0,
			   cheeksBoneHigh = -0.2,
			   eyeBrownHigh = 0,
			 },
			components = {
			   [1] = {
				  texture = 0,
				  component_id = 0,
				  drawable = 0,
				},
			   [2] = {
				  texture = 0,
				  component_id = 1,
				  drawable = 0,
				},
			   [3] = {
				  texture = 0,
				  component_id = 2,
				  drawable = 12,
				},
			   [4] = {
				  texture = 0,
				  component_id = 3,
				  drawable = 60,
				},
			   [5] = {
				  texture = 2,
				  component_id = 4,
				  drawable = 103,
				},
			   [6] = {
				  texture = 0,
				  component_id = 5,
				  drawable = 0,
				},
			   [7] = {
				  texture = 0,
				  component_id = 6,
				  drawable = 75,
				},
			   [8] = {
				  texture = 0,
				  component_id = 7,
				  drawable = 0,
				},
			   [9] = {
				  texture = 0,
				  component_id = 8,
				  drawable = 15,
				},
			   [10] = {
				  texture = 0,
				  component_id = 9,
				  drawable = 0,
				},
			   [11] = {
				  texture = 0,
				  component_id = 10,
				  drawable = 0,
				},
			   [12] = {
				  texture = 2,
				  component_id = 11,
				  drawable = 263,
				},
			 },
			props = {
			   [1] = {
				  texture = -1,
				  prop_id = 0,
				  drawable = -1,
				},
			   [2] = {
				  texture = -1,
				  prop_id = 1,
				  drawable = -1,
				},
			   [3] = {
				  texture = -1,
				  prop_id = 2,
				  drawable = -1,
				},
			   [4] = {
				  texture = -1,
				  prop_id = 6,
				  drawable = -1,
				},
			   [5] = {
				  texture = -1,
				  prop_id = 7,
				  drawable = -1,
				},
			 },
			model = "mp_m_freemode_01",
			tattoos = {
			   ZONE_LEFT_ARM = {
				  [1] = {
					 zone = "ZONE_LEFT_ARM",
					 hashMale = "MP_LR_Tat_022_M",
					 collection = "mplowrider2_overlays",
					 hashFemale = "MP_LR_Tat_022_F",
					 name = "TAT_S2_022",
					 label = "My Crazy Life",
				   },
				},
			   ZONE_RIGHT_ARM = {
				  [1] = {
					 zone = "ZONE_RIGHT_ARM",
					 hashMale = "MP_MP_ImportExport_Tat_003_M",
					 collection = "mpimportexport_overlays",
					 hashFemale = "MP_MP_ImportExport_Tat_003_F",
					 name = "TAT_IE_003",
					 label = "Mechanical Sleeve",
				   },
				},
			 },
			hair = {
			   color = 28,
			   highlight = 38,
			   style = 12,
			 },
			headOverlays = {
			   moleAndFreckles = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   complexion = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   blemishes = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   makeUp = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   lipstick = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   blush = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   beard = {
				  color = 0,
				  opacity = 1,
				  style = 6,
				},
			   bodyBlemishes = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   sunDamage = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   eyebrows = {
				  color = 0,
				  opacity = 1,
				  style = 30,
				},
			   chestHair = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   ageing = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			 },
			headBlend = {
			   shapeSecond = 20,
			   shapeFirst = 21,
			   shapeMix = 0.4,
			   skinFirst = 21,
			   skinSecond = 0,
			   skinMix = 0.3,
			 },
		  },

		  ['f'] = {
			faceFeatures = {
			   nosePeakHigh = 0,
			   jawBoneBackSize = 0,
			   eyeBrownForward = 0,
			   eyesOpening = 0,
			   nosePeakSize = 0,
			   chinBoneSize = 0,
			   cheeksWidth = 0,
			   chinBoneLenght = 0,
			   noseBoneTwist = 0,
			   nosePeakLowering = 0,
			   neckThickness = 0,
			   jawBoneWidth = 0,
			   chinBoneLowering = 0,
			   cheeksBoneWidth = 0,
			   noseBoneHigh = 0,
			   chinHole = 0,
			   eyeBrownHigh = 0,
			   lipsThickness = 0,
			   cheeksBoneHigh = 0,
			   noseWidth = 0,
			 },
			headBlend = {
			   shapeSecond = 0,
			   skinFirst = 12,
			   skinSecond = 0,
			   shapeFirst = 21,
			   shapeMix = 0,
			   skinMix = 0,
			 },
			model = "mp_f_freemode_01",
			hair = {
			   highlight = 55,
			   style = 34,
			   color = 4,
			 },
			tattoos = {
			 },
			eyeColor = 3,
			props = {
			   [1] = {
				  prop_id = 0,
				  texture = -1,
				  drawable = -1,
				},
			   [2] = {
				  prop_id = 1,
				  texture = -1,
				  drawable = -1,
				},
			   [3] = {
				  prop_id = 2,
				  texture = -1,
				  drawable = -1,
				},
			   [4] = {
				  prop_id = 6,
				  texture = -1,
				  drawable = -1,
				},
			   [5] = {
				  prop_id = 7,
				  texture = -1,
				  drawable = -1,
				},
			 },
			headOverlays = {
			   chestHair = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   ageing = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   complexion = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   beard = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   blush = {
				  style = 1,
				  color = 5,
				  opacity = 0.6,
				},
			   moleAndFreckles = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   makeUp = {
				  style = 4,
				  color = 3,
				  opacity = 0.8,
				},
			   eyebrows = {
				  style = 1,
				  color = 5,
				  opacity = 0.9,
				},
			   bodyBlemishes = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   blemishes = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   lipstick = {
				  style = 2,
				  color = 2,
				  opacity = 0.6,
				},
			   sunDamage = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			 },
			components = {
			   [1] = {
				  component_id = 0,
				  texture = 0,
				  drawable = 0,
				},
			   [2] = {
				  component_id = 1,
				  texture = 0,
				  drawable = 0,
				},
			   [3] = {
				  component_id = 2,
				  texture = 0,
				  drawable = 34,
				},
			   [4] = {
				  component_id = 3,
				  texture = 0,
				  drawable = 23,
				},
			   [5] = {
				  component_id = 4,
				  texture = 2,
				  drawable = 62,
				},
			   [6] = {
				  component_id = 5,
				  texture = 0,
				  drawable = 0,
				},
			   [7] = {
				  component_id = 6,
				  texture = 0,
				  drawable = 66,
				},
			   [8] = {
				  component_id = 7,
				  texture = 0,
				  drawable = 90,
				},
			   [9] = {
				  component_id = 8,
				  texture = 0,
				  drawable = 14,
				},
			   [10] = {
				  component_id = 9,
				  texture = 0,
				  drawable = 0,
				},
			   [11] = {
				  component_id = 10,
				  texture = 0,
				  drawable = 0,
				},
			   [12] = {
				  component_id = 11,
				  texture = 2,
				  drawable = 172,
				},
			 },
		  },
	},
	['butcher'] = {
		['m'] = {
			model = "mp_m_freemode_01",
			headBlend = {
			   shapeSecond = 21,
			   skinFirst = 21,
			   skinMix = 0.3,
			   shapeFirst = 31,
			   shapeMix = 0.1,
			   skinSecond = 17,
			 },
			tattoos = {
			   ZONE_HEAD = {
				  [1] = {
					 zone = "ZONE_HEAD",
					 hashMale = "mpHeist3_Tat_019_M",
					 hashFemale = "mpHeist3_Tat_019_F",
					 label = "Teddy Bear",
					 name = "TAT_H3_019",
					 collection = "mpheist3_overlays",
				   },
				  [2] = {
					 zone = "ZONE_HEAD",
					 hashMale = "mpHeist3_Tat_042_M",
					 hashFemale = "mpHeist3_Tat_042_F",
					 label = "Hearts",
					 name = "TAT_H3_042",
					 collection = "mpheist3_overlays",
				   },
				},
			 },
			faceFeatures = {
			   nosePeakLowering = 0.1,
			   cheeksWidth = 0.5,
			   jawBoneBackSize = -1,
			   noseBoneTwist = -0.3,
			   eyeBrownForward = 0,
			   chinHole = 0,
			   eyesOpening = 0.3,
			   chinBoneLenght = 0,
			   eyeBrownHigh = -0.3,
			   lipsThickness = -0.5,
			   noseWidth = -0.8,
			   neckThickness = 0.1,
			   chinBoneSize = 0,
			   cheeksBoneWidth = -0.7,
			   chinBoneLowering = -0.4,
			   nosePeakSize = -0.3,
			   nosePeakHigh = 0.1,
			   cheeksBoneHigh = -0.3,
			   noseBoneHigh = 0,
			   jawBoneWidth = -0.3,
			 },
			components = {
			   [1] = {
				  drawable = 0,
				  component_id = 0,
				  texture = 0,
				},
			   [2] = {
				  drawable = 0,
				  component_id = 1,
				  texture = 0,
				},
			   [3] = {
				  drawable = 31,
				  component_id = 2,
				  texture = 0,
				},
			   [4] = {
				  drawable = 85,
				  component_id = 3,
				  texture = 1,
				},
			   [5] = {
				  drawable = 154,
				  component_id = 4,
				  texture = 5,
				},
			   [6] = {
				  drawable = 0,
				  component_id = 5,
				  texture = 0,
				},
			   [7] = {
				  drawable = 102,
				  component_id = 6,
				  texture = 4,
				},
			   [8] = {
				  drawable = 0,
				  component_id = 7,
				  texture = 0,
				},
			   [9] = {
				  drawable = 15,
				  component_id = 8,
				  texture = 0,
				},
			   [10] = {
				  drawable = 0,
				  component_id = 9,
				  texture = 0,
				},
			   [11] = {
				  drawable = 0,
				  component_id = 10,
				  texture = 0,
				},
			   [12] = {
				  drawable = 14,
				  component_id = 11,
				  texture = 12,
				},
			 },
			eyeColor = 11,
			headOverlays = {
			   complexion = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   sunDamage = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   makeUp = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   ageing = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   blush = {
				  color = 3,
				  opacity = 0.6,
				  style = 1,
				},
			   bodyBlemishes = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   blemishes = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   moleAndFreckles = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   beard = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   chestHair = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   lipstick = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   eyebrows = {
				  color = 0,
				  opacity = 0.7,
				  style = 5,
				},
			 },
			hair = {
			   color = 8,
			   highlight = 31,
			   style = 31,
			 },
			props = {
			   [1] = {
				  drawable = -1,
				  prop_id = 0,
				  texture = -1,
				},
			   [2] = {
				  drawable = 5,
				  prop_id = 1,
				  texture = 2,
				},
			   [3] = {
				  drawable = 5,
				  prop_id = 2,
				  texture = 1,
				},
			   [4] = {
				  drawable = -1,
				  prop_id = 6,
				  texture = -1,
				},
			   [5] = {
				  drawable = -1,
				  prop_id = 7,
				  texture = -1,
				},
			 },
		  },

		  ['f'] = {
			faceFeatures = {
			   nosePeakHigh = 0,
			   jawBoneBackSize = 0,
			   eyeBrownForward = 0,
			   eyesOpening = 0,
			   nosePeakSize = 0,
			   chinBoneSize = 0,
			   cheeksWidth = 0,
			   chinBoneLenght = 0,
			   noseBoneTwist = 0,
			   nosePeakLowering = 0,
			   neckThickness = 0,
			   jawBoneWidth = 0,
			   chinBoneLowering = 0,
			   cheeksBoneWidth = 0,
			   noseBoneHigh = 0,
			   chinHole = 0,
			   eyeBrownHigh = 0,
			   lipsThickness = 0,
			   cheeksBoneHigh = 0,
			   noseWidth = 0,
			 },
			headBlend = {
			   shapeSecond = 0,
			   skinFirst = 12,
			   skinSecond = 0,
			   shapeFirst = 21,
			   shapeMix = 0,
			   skinMix = 0,
			 },
			model = "mp_f_freemode_01",
			hair = {
			   highlight = 55,
			   style = 34,
			   color = 4,
			 },
			tattoos = {
			 },
			eyeColor = 3,
			props = {
			   [1] = {
				  prop_id = 0,
				  texture = -1,
				  drawable = -1,
				},
			   [2] = {
				  prop_id = 1,
				  texture = -1,
				  drawable = -1,
				},
			   [3] = {
				  prop_id = 2,
				  texture = -1,
				  drawable = -1,
				},
			   [4] = {
				  prop_id = 6,
				  texture = -1,
				  drawable = -1,
				},
			   [5] = {
				  prop_id = 7,
				  texture = -1,
				  drawable = -1,
				},
			 },
			headOverlays = {
			   chestHair = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   ageing = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   complexion = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   beard = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   blush = {
				  style = 1,
				  color = 5,
				  opacity = 0.6,
				},
			   moleAndFreckles = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   makeUp = {
				  style = 4,
				  color = 3,
				  opacity = 0.8,
				},
			   eyebrows = {
				  style = 1,
				  color = 5,
				  opacity = 0.9,
				},
			   bodyBlemishes = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   blemishes = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   lipstick = {
				  style = 2,
				  color = 2,
				  opacity = 0.6,
				},
			   sunDamage = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			 },
			components = {
			   [1] = {
				  component_id = 0,
				  texture = 0,
				  drawable = 0,
				},
			   [2] = {
				  component_id = 1,
				  texture = 0,
				  drawable = 0,
				},
			   [3] = {
				  component_id = 2,
				  texture = 0,
				  drawable = 34,
				},
			   [4] = {
				  component_id = 3,
				  texture = 0,
				  drawable = 100,
				},
			   [5] = {
				  component_id = 4,
				  texture = 22,
				  drawable = 115,
				},
			   [6] = {
				  component_id = 5,
				  texture = 0,
				  drawable = 0,
				},
			   [7] = {
				  component_id = 6,
				  texture = 3,
				  drawable = 66,
				},
			   [8] = {
				  component_id = 7,
				  texture = 0,
				  drawable = 85,
				},
			   [9] = {
				  component_id = 8,
				  texture = 0,
				  drawable = 14,
				},
			   [10] = {
				  component_id = 9,
				  texture = 0,
				  drawable = 67,
				},
			   [11] = {
				  component_id = 10,
				  texture = 0,
				  drawable = 0,
				},
			   [12] = {
				  component_id = 11,
				  texture = 0,
				  drawable = 392,
				},
			 },
		  },
	},

	['warehouse'] = {
		['m'] = {
			headOverlays = {
			   bodyBlemishes = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   sunDamage = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   moleAndFreckles = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   blush = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   eyebrows = {
				  style = 30,
				  color = 0,
				  opacity = 1,
				},
			   chestHair = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   ageing = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   beard = {
				  style = 3,
				  color = 0,
				  opacity = 1,
				},
			   complexion = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   makeUp = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   blemishes = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   lipstick = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			 },
			headBlend = {
			   shapeFirst = 2,
			   shapeMix = 0,
			   shapeSecond = 0,
			   skinSecond = 14,
			   skinFirst = 0,
			   skinMix = 1,
			 },
			tattoos = {
			 },
			props = {
			   [1] = {
				  texture = 3,
				  drawable = 22,
				  prop_id = 0,
				},
			   [2] = {
				  texture = 0,
				  drawable = 0,
				  prop_id = 1,
				},
			   [3] = {
				  texture = -1,
				  drawable = -1,
				  prop_id = 2,
				},
			   [4] = {
				  texture = -1,
				  drawable = -1,
				  prop_id = 6,
				},
			   [5] = {
				  texture = -1,
				  drawable = -1,
				  prop_id = 7,
				},
			 },
			hair = {
			   style = 184,
			   highlight = 54,
			   color = 54,
			 },
			eyeColor = 0,
			model = "mp_m_freemode_01",
			components = {
			   [1] = {
				  texture = 0,
				  drawable = 0,
				  component_id = 0,
				},
			   [2] = {
				  texture = 0,
				  drawable = 0,
				  component_id = 1,
				},
			   [3] = {
				  texture = 0,
				  drawable = 184,
				  component_id = 2,
				},
			   [4] = {
				  texture = 0,
				  drawable = 17,
				  component_id = 3,
				},
			   [5] = {
				  texture = 20,
				  drawable = 153,
				  component_id = 4,
				},
			   [6] = {
				  texture = 0,
				  drawable = 0,
				  component_id = 5,
				},
			   [7] = {
				  texture = 0,
				  drawable = 76,
				  component_id = 6,
				},
			   [8] = {
				  texture = 0,
				  drawable = 0,
				  component_id = 7,
				},
			   [9] = {
				  texture = 0,
				  drawable = 15,
				  component_id = 8,
				},
			   [10] = {
				  texture = 0,
				  drawable = 0,
				  component_id = 9,
				},
			   [11] = {
				  texture = 0,
				  drawable = 0,
				  component_id = 10,
				},
			   [12] = {
				  texture = 0,
				  drawable = 263,
				  component_id = 11,
				},
			 },
			faceFeatures = {
			   noseWidth = 0,
			   jawBoneBackSize = 0,
			   cheeksBoneWidth = 0,
			   nosePeakSize = 0,
			   lipsThickness = 0,
			   chinHole = 0,
			   chinBoneLowering = 0,
			   cheeksBoneHigh = 0,
			   eyesOpening = 0,
			   nosePeakLowering = 0,
			   noseBoneHigh = 0,
			   eyeBrownHigh = 0,
			   chinBoneSize = 0,
			   nosePeakHigh = 0,
			   cheeksWidth = 0,
			   noseBoneTwist = 0,
			   chinBoneLenght = 0,
			   eyeBrownForward = 0,
			   neckThickness = 0,
			   jawBoneWidth = 0,
			 },
		  },

		  ['f'] = {
			faceFeatures = {
			   nosePeakHigh = 0,
			   jawBoneBackSize = 0,
			   eyeBrownForward = 0,
			   eyesOpening = 0,
			   nosePeakSize = 0,
			   chinBoneSize = 0,
			   cheeksWidth = 0,
			   chinBoneLenght = 0,
			   noseBoneTwist = 0,
			   nosePeakLowering = 0,
			   neckThickness = 0,
			   jawBoneWidth = 0,
			   chinBoneLowering = 0,
			   cheeksBoneWidth = 0,
			   noseBoneHigh = 0,
			   chinHole = 0,
			   eyeBrownHigh = 0,
			   lipsThickness = 0,
			   cheeksBoneHigh = 0,
			   noseWidth = 0,
			 },
			headBlend = {
			   shapeSecond = 0,
			   skinFirst = 12,
			   skinSecond = 0,
			   shapeFirst = 21,
			   shapeMix = 0,
			   skinMix = 0,
			 },
			model = "mp_f_freemode_01",
			hair = {
			   highlight = 55,
			   style = 34,
			   color = 4,
			 },
			tattoos = {
			 },
			eyeColor = 3,
			props = {
			   [1] = {
				  prop_id = 0,
				  texture = -1,
				  drawable = -1,
				},
			   [2] = {
				  prop_id = 1,
				  texture = -1,
				  drawable = -1,
				},
			   [3] = {
				  prop_id = 2,
				  texture = -1,
				  drawable = -1,
				},
			   [4] = {
				  prop_id = 6,
				  texture = -1,
				  drawable = -1,
				},
			   [5] = {
				  prop_id = 7,
				  texture = -1,
				  drawable = -1,
				},
			 },
			headOverlays = {
			   chestHair = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   ageing = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   complexion = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   beard = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   blush = {
				  style = 1,
				  color = 5,
				  opacity = 0.6,
				},
			   moleAndFreckles = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   makeUp = {
				  style = 4,
				  color = 3,
				  opacity = 0.8,
				},
			   eyebrows = {
				  style = 1,
				  color = 5,
				  opacity = 0.9,
				},
			   bodyBlemishes = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   blemishes = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   lipstick = {
				  style = 2,
				  color = 2,
				  opacity = 0.6,
				},
			   sunDamage = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			 },
			components = {
			   [1] = {
				  component_id = 0,
				  texture = 0,
				  drawable = 0,
				},
			   [2] = {
				  component_id = 1,
				  texture = 0,
				  drawable = 0,
				},
			   [3] = {
				  component_id = 2,
				  texture = 0,
				  drawable = 34,
				},
			   [4] = {
				  component_id = 3,
				  texture = 0,
				  drawable = 22,
				},
			   [5] = {
				  component_id = 4,
				  texture = 20,
				  drawable = 115,
				},
			   [6] = {
				  component_id = 5,
				  texture = 0,
				  drawable = 0,
				},
			   [7] = {
				  component_id = 6,
				  texture = 0,
				  drawable = 64,
				},
			   [8] = {
				  component_id = 7,
				  texture = 0,
				  drawable = 85,
				},
			   [9] = {
				  component_id = 8,
				  texture = 0,
				  drawable = 14,
				},
			   [10] = {
				  component_id = 9,
				  texture = 0,
				  drawable = 67,
				},
			   [11] = {
				  component_id = 10,
				  texture = 0,
				  drawable = 0,
				},
			   [12] = {
				  component_id = 11,
				  texture = 0,
				  drawable = 172,
				},
			 },
		  },
	},
	['garbage'] = {
		['m'] = {
			eyeColor = 26,
			faceFeatures = {
		   eyesOpening = 0,
		   lipsThickness = -0.4,
		   cheeksWidth = 0.5,
		   noseBoneHigh = 0.1,
		   nosePeakHigh = 0,
		   jawBoneBackSize = -0.2,
		   chinBoneLowering = 0,
		   chinHole = 0,
		   eyeBrownForward = 0,
		   noseBoneTwist = -0.3,
		   jawBoneWidth = -0.2,
		   nosePeakSize = -0.1,
		   chinBoneLenght = 0,
		   nosePeakLowering = 0.1,
		   cheeksBoneWidth = -1,
		   noseWidth = -0.5,
		   chinBoneSize = 0,
		   neckThickness = 0,
		   cheeksBoneHigh = -0.2,
		   eyeBrownHigh = 0,
		 },
		components = {
		   [1] = {
			  texture = 0,
			  component_id = 0,
			  drawable = 0,
			},
		   [2] = {
			  texture = 0,
			  component_id = 1,
			  drawable = 0,
			},
		   [3] = {
			  texture = 0,
			  component_id = 2,
			  drawable = 12,
			},
		   [4] = {
			  texture = 0,
			  component_id = 3,
			  drawable = 63,
			},
		   [5] = {
			  texture = 0,
			  component_id = 4,
			  drawable = 83,
			},
		   [6] = {
			  texture = 0,
			  component_id = 5,
			  drawable = 0,
			},
		   [7] = {
			  texture = 0,
			  component_id = 6,
			  drawable = 75,
			},
		   [8] = {
			  texture = 0,
			  component_id = 7,
			  drawable = 0,
			},
		   [9] = {
			  texture = 0,
			  component_id = 8,
			  drawable = 15,
			},
		   [10] = {
			  texture = 4,
			  component_id = 9,
			  drawable = 16,
			},
		   [11] = {
			  texture = 0,
			  component_id = 10,
			  drawable = 0,
			},
		   [12] = {
			  texture = 0,
			  component_id = 11,
			  drawable = 470,
			},
		 },
		props = {
		   [1] = {
			  texture = -1,
			  prop_id = 0,
			  drawable = -1,
			},
		   [2] = {
			  texture = -1,
			  prop_id = 1,
			  drawable = -1,
			},
		   [3] = {
			  texture = -1,
			  prop_id = 2,
			  drawable = -1,
			},
		   [4] = {
			  texture = -1,
			  prop_id = 6,
			  drawable = -1,
			},
		   [5] = {
			  texture = -1,
			  prop_id = 7,
			  drawable = -1,
			},
		 },
		model = "mp_m_freemode_01",
		tattoos = {
		   ZONE_LEFT_ARM = {
			  [1] = {
				 zone = "ZONE_LEFT_ARM",
				 hashMale = "MP_LR_Tat_022_M",
				 collection = "mplowrider2_overlays",
				 hashFemale = "MP_LR_Tat_022_F",
				 name = "TAT_S2_022",
				 label = "My Crazy Life",
			   },
			},
		   ZONE_RIGHT_ARM = {
			  [1] = {
				 zone = "ZONE_RIGHT_ARM",
				 hashMale = "MP_MP_ImportExport_Tat_003_M",
				 collection = "mpimportexport_overlays",
				 hashFemale = "MP_MP_ImportExport_Tat_003_F",
				 name = "TAT_IE_003",
				 label = "Mechanical Sleeve",
			   },
			},
		 },
		hair = {
		   color = 28,
		   highlight = 38,
		   style = 12,
		 },
		headOverlays = {
		   moleAndFreckles = {
			  color = 0,
			  opacity = 0,
			  style = 0,
			},
		   complexion = {
			  color = 0,
			  opacity = 0,
			  style = 0,
			},
		   blemishes = {
			  color = 0,
			  opacity = 0,
			  style = 0,
			},
		   makeUp = {
			  color = 0,
			  opacity = 0,
			  style = 0,
			},
		   lipstick = {
			  color = 0,
			  opacity = 0,
			  style = 0,
			},
		   blush = {
			  color = 0,
			  opacity = 0,
			  style = 0,
			},
		   beard = {
			  color = 0,
			  opacity = 1,
			  style = 6,
			},
		   bodyBlemishes = {
			  color = 0,
			  opacity = 0,
			  style = 0,
			},
		   sunDamage = {
			  color = 0,
			  opacity = 0,
			  style = 0,
			},
		   eyebrows = {
			  color = 0,
			  opacity = 1,
			  style = 30,
			},
		   chestHair = {
			  color = 0,
			  opacity = 0,
			  style = 0,
			},
		   ageing = {
			  color = 0,
			  opacity = 0,
			  style = 0,
			},
		 },
		headBlend = {
		   shapeSecond = 20,
		   shapeFirst = 21,
		   shapeMix = 0.4,
		   skinFirst = 21,
		   skinSecond = 0,
		   skinMix = 0.3,
		 },
	  },
	  ['f'] = {
		faceFeatures = {
		   nosePeakHigh = 0,
		   jawBoneBackSize = 0,
		   eyeBrownForward = 0,
		   eyesOpening = 0,
		   nosePeakSize = 0,
		   chinBoneSize = 0,
		   cheeksWidth = 0,
		   chinBoneLenght = 0,
		   noseBoneTwist = 0,
		   nosePeakLowering = 0,
		   neckThickness = 0,
		   jawBoneWidth = 0,
		   chinBoneLowering = 0,
		   cheeksBoneWidth = 0,
		   noseBoneHigh = 0,
		   chinHole = 0,
		   eyeBrownHigh = 0,
		   lipsThickness = 0,
		   cheeksBoneHigh = 0,
		   noseWidth = 0,
		 },
		headBlend = {
		   shapeSecond = 0,
		   skinFirst = 12,
		   skinSecond = 0,
		   shapeFirst = 21,
		   shapeMix = 0,
		   skinMix = 0,
		 },
		model = "mp_f_freemode_01",
		hair = {
		   highlight = 55,
		   style = 34,
		   color = 4,
		 },
		tattoos = {
		 },
		eyeColor = 3,
		props = {
		   [1] = {
			  prop_id = 0,
			  texture = -1,
			  drawable = -1,
			},
		   [2] = {
			  prop_id = 1,
			  texture = -1,
			  drawable = -1,
			},
		   [3] = {
			  prop_id = 2,
			  texture = -1,
			  drawable = -1,
			},
		   [4] = {
			  prop_id = 6,
			  texture = -1,
			  drawable = -1,
			},
		   [5] = {
			  prop_id = 7,
			  texture = -1,
			  drawable = -1,
			},
		 },
		headOverlays = {
		   chestHair = {
			  style = 0,
			  color = 0,
			  opacity = 0,
			},
		   ageing = {
			  style = 0,
			  color = 0,
			  opacity = 0,
			},
		   complexion = {
			  style = 0,
			  color = 0,
			  opacity = 0,
			},
		   beard = {
			  style = 0,
			  color = 0,
			  opacity = 0,
			},
		   blush = {
			  style = 1,
			  color = 5,
			  opacity = 0.6,
			},
		   moleAndFreckles = {
			  style = 0,
			  color = 0,
			  opacity = 0,
			},
		   makeUp = {
			  style = 4,
			  color = 3,
			  opacity = 0.8,
			},
		   eyebrows = {
			  style = 1,
			  color = 5,
			  opacity = 0.9,
			},
		   bodyBlemishes = {
			  style = 0,
			  color = 0,
			  opacity = 0,
			},
		   blemishes = {
			  style = 0,
			  color = 0,
			  opacity = 0,
			},
		   lipstick = {
			  style = 2,
			  color = 2,
			  opacity = 0.6,
			},
		   sunDamage = {
			  style = 0,
			  color = 0,
			  opacity = 0,
			},
		 },
		components = {
		   [1] = {
			  component_id = 0,
			  texture = 0,
			  drawable = 0,
			},
		   [2] = {
			  component_id = 1,
			  texture = 0,
			  drawable = 0,
			},
		   [3] = {
			  component_id = 2,
			  texture = 0,
			  drawable = 34,
			},
		   [4] = {
			  component_id = 3,
			  texture = 0,
			  drawable = 76,
			},
		   [5] = {
			  component_id = 4,
			  texture = 1,
			  drawable = 41,
			},
		   [6] = {
			  component_id = 5,
			  texture = 0,
			  drawable = 0,
			},
		   [7] = {
			  component_id = 6,
			  texture = 0,
			  drawable = 49,
			},
		   [8] = {
			  component_id = 7,
			  texture = 0,
			  drawable = 85,
			},
		   [9] = {
			  component_id = 8,
			  texture = 0,
			  drawable = 14,
			},
		   [10] = {
			  component_id = 9,
			  texture = 0,
			  drawable = 5,
			},
		   [11] = {
			  component_id = 10,
			  texture = 0,
			  drawable = 0,
			},
		   [12] = {
			  component_id = 11,
			  texture = 0,
			  drawable = 135,
			},
		 },
	  }
	},
	['taxi'] = {
		['m'] = {
			model = "mp_m_freemode_01",
			headBlend = {
			   shapeSecond = 21,
			   skinFirst = 21,
			   skinMix = 0.3,
			   shapeFirst = 31,
			   shapeMix = 0.1,
			   skinSecond = 17,
			 },
			tattoos = {
			   ZONE_HEAD = {
				  [1] = {
					 zone = "ZONE_HEAD",
					 hashMale = "mpHeist3_Tat_019_M",
					 hashFemale = "mpHeist3_Tat_019_F",
					 label = "Teddy Bear",
					 name = "TAT_H3_019",
					 collection = "mpheist3_overlays",
				   },
				  [2] = {
					 zone = "ZONE_HEAD",
					 hashMale = "mpHeist3_Tat_042_M",
					 hashFemale = "mpHeist3_Tat_042_F",
					 label = "Hearts",
					 name = "TAT_H3_042",
					 collection = "mpheist3_overlays",
				   },
				},
			 },
			faceFeatures = {
			   nosePeakLowering = 0.1,
			   cheeksWidth = 0.5,
			   jawBoneBackSize = -1,
			   noseBoneTwist = -0.3,
			   eyeBrownForward = 0,
			   chinHole = 0,
			   eyesOpening = 0.3,
			   chinBoneLenght = 0,
			   eyeBrownHigh = -0.3,
			   lipsThickness = -0.5,
			   noseWidth = -0.8,
			   neckThickness = 0.1,
			   chinBoneSize = 0,
			   cheeksBoneWidth = -0.7,
			   chinBoneLowering = -0.4,
			   nosePeakSize = -0.3,
			   nosePeakHigh = 0.1,
			   cheeksBoneHigh = -0.3,
			   noseBoneHigh = 0,
			   jawBoneWidth = -0.3,
			 },
			components = {
			   [1] = {
				  drawable = 0,
				  component_id = 0,
				  texture = 0,
				},
			   [2] = {
				  drawable = 0,
				  component_id = 1,
				  texture = 0,
				},
			   [3] = {
				  drawable = 31,
				  component_id = 2,
				  texture = 0,
				},
			   [4] = {
				  drawable = 26,
				  component_id = 3,
				  texture = 0,
				},
			   [5] = {
				  drawable = 111,
				  component_id = 4,
				  texture = 0,
				},
			   [6] = {
				  drawable = 0,
				  component_id = 5,
				  texture = 0,
				},
			   [7] = {
				  drawable = 74,
				  component_id = 6,
				  texture = 0,
				},
			   [8] = {
				  drawable = 0,
				  component_id = 7,
				  texture = 0,
				},
			   [9] = {
				  drawable = 15,
				  component_id = 8,
				  texture = 0,
				},
			   [10] = {
				  drawable = 0,
				  component_id = 9,
				  texture = 0,
				},
			   [11] = {
				  drawable = 0,
				  component_id = 10,
				  texture = 0,
				},
			   [12] = {
				  drawable = 419,
				  component_id = 11,
				  texture = 13,
				},
			 },
			eyeColor = 11,
			headOverlays = {
			   complexion = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   sunDamage = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   makeUp = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   ageing = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   blush = {
				  color = 3,
				  opacity = 0.6,
				  style = 1,
				},
			   bodyBlemishes = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   blemishes = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   moleAndFreckles = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   beard = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   chestHair = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   lipstick = {
				  color = 0,
				  opacity = 0,
				  style = 0,
				},
			   eyebrows = {
				  color = 0,
				  opacity = 0.7,
				  style = 5,
				},
			 },
			hair = {
			   color = 8,
			   highlight = 31,
			   style = 31,
			 },
			props = {
			   [1] = {
				  drawable = -1,
				  prop_id = 0,
				  texture = -1,
				},
			   [2] = {
				  drawable = 5,
				  prop_id = 1,
				  texture = 2,
				},
			   [3] = {
				  drawable = 5,
				  prop_id = 2,
				  texture = 1,
				},
			   [4] = {
				  drawable = -1,
				  prop_id = 6,
				  texture = -1,
				},
			   [5] = {
				  drawable = -1,
				  prop_id = 7,
				  texture = -1,
				},
			 },
		  },
		  ['f'] = {
			faceFeatures = {
			   nosePeakHigh = 0,
			   jawBoneBackSize = 0,
			   eyeBrownForward = 0,
			   eyesOpening = 0,
			   nosePeakSize = 0,
			   chinBoneSize = 0,
			   cheeksWidth = 0,
			   chinBoneLenght = 0,
			   noseBoneTwist = 0,
			   nosePeakLowering = 0,
			   neckThickness = 0,
			   jawBoneWidth = 0,
			   chinBoneLowering = 0,
			   cheeksBoneWidth = 0,
			   noseBoneHigh = 0,
			   chinHole = 0,
			   eyeBrownHigh = 0,
			   lipsThickness = 0,
			   cheeksBoneHigh = 0,
			   noseWidth = 0,
			 },
			headBlend = {
			   shapeSecond = 0,
			   skinFirst = 12,
			   skinSecond = 0,
			   shapeFirst = 21,
			   shapeMix = 0,
			   skinMix = 0,
			 },
			model = "mp_f_freemode_01",
			hair = {
			   highlight = 55,
			   style = 34,
			   color = 4,
			 },
			tattoos = {
			 },
			eyeColor = 3,
			props = {
			   [1] = {
				  prop_id = 0,
				  texture = -1,
				  drawable = -1,
				},
			   [2] = {
				  prop_id = 1,
				  texture = -1,
				  drawable = -1,
				},
			   [3] = {
				  prop_id = 2,
				  texture = -1,
				  drawable = -1,
				},
			   [4] = {
				  prop_id = 6,
				  texture = -1,
				  drawable = -1,
				},
			   [5] = {
				  prop_id = 7,
				  texture = -1,
				  drawable = -1,
				},
			 },
			headOverlays = {
			   chestHair = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   ageing = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   complexion = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   beard = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   blush = {
				  style = 1,
				  color = 5,
				  opacity = 0.6,
				},
			   moleAndFreckles = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   makeUp = {
				  style = 4,
				  color = 3,
				  opacity = 0.8,
				},
			   eyebrows = {
				  style = 1,
				  color = 5,
				  opacity = 0.9,
				},
			   bodyBlemishes = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   blemishes = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			   lipstick = {
				  style = 2,
				  color = 2,
				  opacity = 0.6,
				},
			   sunDamage = {
				  style = 0,
				  color = 0,
				  opacity = 0,
				},
			 },
			components = {
			   [1] = {
				  component_id = 0,
				  texture = 0,
				  drawable = 0,
				},
			   [2] = {
				  component_id = 1,
				  texture = 0,
				  drawable = 0,
				},
			   [3] = {
				  component_id = 2,
				  texture = 0,
				  drawable = 34,
				},
			   [4] = {
				  component_id = 3,
				  texture = 0,
				  drawable = 14,
				},
			   [5] = {
				  component_id = 4,
				  texture = 0,
				  drawable = 6,
				},
			   [6] = {
				  component_id = 5,
				  texture = 0,
				  drawable = 0,
				},
			   [7] = {
				  component_id = 6,
				  texture = 0,
				  drawable = 41,
				},
			   [8] = {
				  component_id = 7,
				  texture = 0,
				  drawable = 1,
				},
			   [9] = {
				  component_id = 8,
				  texture = 0,
				  drawable = 14,
				},
			   [10] = {
				  component_id = 9,
				  texture = 0,
				  drawable = 0,
				},
			   [11] = {
				  component_id = 10,
				  texture = 0,
				  drawable = 0,
				},
			   [12] = {
				  component_id = 11,
				  texture = 1,
				  drawable = 469,
				},
			 },
		  }
	}
}